listen:
  host: localhost # not implemented
  port: 8080

storage:
  path: /tmp/packages
  maxFileSize: 4G

security:
  secret: anchor2

postgres:
  host: 127.0.0.1
  port: 5432
  db: ar2
  username: ar2
  password: ar2

